# Общие настройки для всех профилей
spring:
  application:
    name: kasko-service
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
  actuator:
    endpoints:
      web:
        exposure:
          include: health, info, metrics
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  tomcat:
    uri-encoding: UTF-8
---
# Настройки для профиля test
spring:
  profiles:
    active: "test"
  datasource:
    url: jdbc:h2:mem:kasko_dev;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kasko_dev
      username: root
      password: example
  kafka:
    bootstrap-servers: localhost:29092
  logging:
    level:
      root: INFO
      ru.motorinsurance: DEBUG
    logstash:
      url: localhost:5044 # Адрес Logstash
    file:
      path: ./logs
      name: ${logging.file.path}/${spring.application.name}.log
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

---
# Настройки для профиля prod
spring:
  profiles:
    active: "prod"
  datasource:
    url: jdbc:postgresql://localhost:5432/kasko_db
    username: kasko
    password: kasko123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kasko_db
      username: root
      password: example
      authentication-database: admin
  kafka:
    bootstrap-servers: kafka:9092
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public
    user: kasko
    password: kasko123
    url: jdbc:postgresql://localhost:5432/kasko_db
  management:
    endpoints:
      web:
        exposure:
          include: health, info, prometheus, env
  logging:
    level:
      root: INFO
      org.hibernate.SQL: WARN
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN