# Общие настройки для всех профилей
spring:
  application:
    name: kasko-service
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
  actuator:
    endpoints:
      web:
        exposure:
          include: health, info, metrics
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  tomcat:
    uri-encoding: UTF-8